### ISSUE TITLE
Feature: GitDevClean command

### ISSUE THREAD

**Issue by b0o** [moyiz/git-dev.nvim#10]
It would be nice to have a `GitDevClean` command to clean the current repo if no args are passed, which would close all buffers that are open containing files from the repo and then delete the repo directory. 

The command could also support an argument to clean a specific repo, e.g. `GitDevClean moyiz/git-dev.nvim` would only clean the given repo. 

Additionally, it would be nice if the repo name was tab-completable from the list of local cached repos.

**Comment by moyiz** [comment]
A great idea.
I finally found the time to implement it.

Two new functions and commands:
- `close_buffers()`, `GitDevCloseBuffers`
- `clean()`, `GitDevClean`

Both accept optional repository and ref. If omitted, they will default to associated repository of current buffer.
Both commands support auto-completion.
