### ISSUE TITLE
Some new update is forcing all files to be readonly

### ISSUE THREAD

**Issue by derekbunch** [moyiz/git-dev.nvim#13]
I started experiencing weird behavior from neovim today, where every file I would open in neovim would be opened as non-modifiable readonly by default. I did some testing with my plugins and narrowed it down to this plugin.

my config is the barebones config defined in the readme
```
return {
  "moyiz/git-dev.nvim",
  event = "VeryLazy",
  opts = {},
}
```

i also tried the "even lazier version" and everything is fine until i try to use any git-dev command (at which it imports the plugin and turns every buffer to read only.

let me know if there is any other information i can provide to help debug this issue, as I really appreciate this plugin and would love to be able to continue using it!

```zsh
nvim --version
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1693350652

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/nix/store/gbns4aw2wrrf5p821jg0q1fcspm7i3hn-neovim-unwrapped-0.9.5/share/nvim
"

Run :checkhealth for more info
```
I am also using LazyVim for context

**Comment by derekbunch** [comment]
I've reverted to tag = "v0.3.0" for now as it does not appear to have the issue.

**Comment by derekbunch** [comment]
i think ive found the issue 

```
if config.read_only then
      -- Set all buffers in the repository directory as read-only
      -- and unmodifiable.
      ui:print "Setting read only mode..."
      vim.api.nvim_create_autocmd({ "BufReadPost" }, {
        group = augroup,
        pattern = repo_dir .. "*",
        callback = function()
          vim.cmd "setlocal readonly nomodifiable"
        end,
      })
```
with a default of `M.read_only = true` doesn't just set buffers for remote repositories to readonly, unmodifiable. it sets any file opened in neovim to readonly, unmodifiable (at least in my experience)

**Comment by moyiz** [comment]
Thanks for creating an issue and the kind words.

Unfortunately I was not able to reproduce it in v0.9.5 and v0.10.

Follow up questions:
- Is it reproducible with any URI?

> where every file I would open in neovim would be opened as non-modifiable readonly by default.

- Where were the files located (relative to `repo_dir`)?
- Did `repo_dir` exist prior to calling `GitDevOpen`?

**Comment by derekbunch** [comment]
it happens without any URI, just as soon as the plugin is loaded. I took a small video that hopefully might make it a bit more clear.
https://github.com/moyiz/git-dev.nvim/assets/30882136/94ba57fc-718c-4e24-a986-a127db147cc0

the files are just my neovim config (the video is in my plugins directory)

**Comment by moyiz** [comment]
Thanks for the clarification.
The issue seems to relate to how the UI class sets the output buffer. The autocmd above should only be created when `open` is called. 

I am not sure yet why I could not reproduce, but the the following PR should solve it.
Can you please check?
Branch: `fix-ui-buffer`

Notice that if it does, the branch will be deleted after merge so do not forget to change it back.

**Comment by derekbunch** [comment]
this resolved my issue, thanks again for the help and quick response!!
