### ISSUE TITLE
[Feature Request] Support for git@

### ISSUE THREAD

**Issue by snoweuph** [moyiz/git-dev.nvim#16]
It would be awesome to also support `git@`urls, so that users don't need to care about which one they used in the browser

**Comment by moyiz** [comment]
Thanks for creating a feature request.

What do you mean? Git SSH URIs are currently supported.

**Comment by moyiz** [comment]
No worries. It makes sense to support URL decoding in the builtin parser, I will reference this issue once it is merged.

**Comment by snoweuph** [comment]
ahh okay
